name = "intent"
license = "MIT"
licenselink = "https://github.com/factor10/intent/LICENCE.md"
description = "Theme for Intent documentation"
homepage = "https://factor10.github.io/intent"
tags = ["", ""]
features = ["", ""]
min_version = "0.54.0"
