baseURL = "https://factor10.github.com/intent"
languageCode = "en-us"
title = "Intent"
theme = "intent"

pygmentsuseclasses = false

[menu]

  [[menu.main]]
    identifier = "introduction"
    name = "Introduction"
    url = "/"
    weight = 100

  [[menu.main]]
    parent = "introduction"
    name = "Getting started"
    url = "#getting-started"
    weight = 100

  [[menu.main]]
    parent = "introduction"
    name = "Why a new framework"
    url = "#why-a-new-test-framework"
    weight = 110

  [[menu.main]]
    parent = "introduction"
    name = "Contributing"
    url = "#contributing-to-intent"
    weight = 120

  [[menu.main]]
    parent = "introduction"
    name = "Find us at GitHub"
    url = "https://github.com/factor10/intent"
    weight = 120

  [[menu.main]]
    identifier = "types"
    name = "Types of tests"
    url = "/types-of-tests/stateless/"
    weight = 200

  [[menu.main]]
    parent = "types"
    name = "Stateless"
    url = "/types-of-tests/stateless/"
    weight = 100

  [[menu.main]]
    parent = "types"
    name = "Stateful"
    url = "/types-of-tests/stateful/"
    weight = 110

  [[menu.main]]
    parent = "types"
    name = "Asynchronous"
    url = "/types-of-tests/asynchronous/"
    weight = 120

  [[menu.main]]
    parent = "types"
    name = "Table-driven"
    url = "/types-of-tests/table-driven/"
    weight = 130

  [[menu.main]]
    identifier = "matchers"
    name = "Matchers"
    url = "/matchers/"
    weight = 300
